baseurl = "https://jackklika.com" # Hostname (and path) to the root.
title = "jackklika" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Jack Klika" # Author's name.
    info = "Software | Chinese" # Author's job title or info.
    description = "Jack's Website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jackklika/"
[[params.social]]
    name = "Gitlab"
    weight = 2
    url = "https://gitlab.com/jackklika/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/jack-klika-55915912a/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "https://blog.jackklika.com"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Library"
    weight = 3
    url = "https://library.jackklika.com"
[[menu.main]]
    name = "Projects"
    weight = 4
    url = "/projects/"
